name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: sudo rm -f package-lock.json
    - run: sudo npm install
    # - run: sudo npm run build --if-present
    # - run: sudo npm run start --if-present
    # - run: sudo pm2 start npm --name "server-gaitan" -- start
    # - run: pm2 reload server-gaitan
    #
